sh chg.sh cn_abbAyi.p 
sh chg.sh cn_aMwa.p 
sh chg.sh cn_bAludu.p 
sh chg.sh cn_baMdi.p 
sh chg.sh cn_beVMdu.p 
sh chg.sh cn_bonu.p 
sh chg.sh cn_buddi.p 
sh chg.sh cn_cenu.p 
sh chg.sh cn_cillu.p 
sh chg.sh cn_eVnimixi.p 
sh chg.sh cn_gaxi.p 
sh chg.sh cn_goru.p 
sh chg.sh cn_goyi.p 
sh chg.sh cn_guddu.p 
sh chg.sh cn_gudi.p 
sh chg.sh cn_gUdu.p 
sh chg.sh cn_guMdu.p 
sh chg.sh cn_illu.p 
sh chg.sh cn_kalcar.p 
sh chg.sh cn_kannu.p 
sh chg.sh cn_kIlu.p 
sh chg.sh cn_kota.p 
sh chg.sh cn_koti.p 
sh chg.sh cn_kotu.p 
sh chg.sh cn_koVttu.p 
sh chg.sh cn_kuMxelu.p 
sh chg.sh cn_maMxi.p 
sh chg.sh cn_maniRi.p 
sh chg.sh cn_maniRi.p.n 
sh chg.sh cn_meku.p 
sh chg.sh cn_meVxadu.p 
sh chg.sh cn_nOkaru.p 
sh chg.sh cn_nUru.p 
sh chg.sh cn_pAlu.p 
sh chg.sh cn_paMxeVM.p 
sh chg.sh cn_paMxiri.p 
sh chg.sh cn_pani.p 
sh chg.sh cn_peVnnu.p 
sh chg.sh cn_peVtteV.p 
sh chg.sh cn_pillavAdu.p 
sh chg.sh cn_piMdi.p 
sh chg.sh cn_puli.p 
sh chg.sh cn_puswakaM.p 
sh chg.sh cn_putti.p 
sh chg.sh cn_pUvu.p 
sh chg.sh cn_rANi.p 
sh chg.sh cn_rAwri.p 
sh chg.sh cn_rikRA.p 
sh chg.sh cn_snehiwudu.p 
sh chg.sh cn_Uru.p 
sh chg.sh cn_velu.p 
sh chg.sh cn_veVyyi.p 
sh chg.sh cn_wiragali.p 
sh chg.sh cn_xAri.p 
sh chg.sh cn_xrAyi.p 
