lA ninna lA
mIxa akkada mIxa
aMwa moVxata aMwa
bEta moVxata bEta
cotu moVxata cotu
kAda akkada kAda
lona ninna lona
pEna akkada pEna
sepu munupu sepu
apudu appudu apudu
kiMxa akkada kiMxa
muMxu moVxata muMxu
ninna ninna ninna
pakka ninna pakka
aMwata moVxata aMwata
appudu appudu appudu
bayata moVxata bayata
civara moVxata civara
eVxata moVxata eVxata
eVxuta moVxata eVxuta
kriMxa akkada kriMxa
lopala ninna lopala
lopata akkada lopata
mIxata moVxata mIxata
munupu munupu munupu
nuxuta moVxata nuxuta
varaku munupu varaku
avawala akkada avawala
kiMxata moVxata kiMxata
moVxata moVxata moVxata
muMgita moVxata muMgita
muMxata moVxata muMxata
muMxuta moVxata muMxuta
noVsata moVxata noVsata
pakkana akkada pakkana
veVnaka ninna veVnaka
veVnuka ninna veVnuka
warvAwa moVxata warvAwa
xaggara moVxata xaggara
xaggira moVxata xaggira
kadapata akkada kadapata
padamata moVxata padamata
waravAwa moVxata waravAwa
waruvAwa moVxata waruvAwa
kriMxata moVxata kriMxata
poVxxuta moVxata poVxxuta
proVxxuta moVxata proVxxuta
cinnappudu appudu cinnappudu
cittacivara moVxata cittacivara
eVttaeVxuta moVxata eVttaeVxuta
cuttupakkala akkada cuttupakkala
cuttuprakkala akkada cuttuprakkala
moVttamoVxata moVxata mottamoVxata
